# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20161024_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='has_perm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
