# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20161024_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='has_module_perms',
        ),
        migrations.RemoveField(
            model_name='account',
            name='has_perm',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_superuser',
        ),
    ]
