# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auto_caption',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_caption',
            new_name='title',
        ),
    ]
