# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20161115_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default='Title'),
        ),
    ]
