# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20161120_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
